name: builder_static_text
description: Simple way to add some static text into generated source files.
version: 0.1.0
author: Herbert Poul <herbert@poul.at>
homepage: https://github.com/hpoul/builder_static_text

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.1
  source_gen: ^1.0.0

dev_dependencies:

